site_name: NungKup101
docs_dir: 'docs/'
copyright: 'Copyright &copy; Thanakrit 2023'
site_author: 'TKN'
site_url: 'https://thanakrit1997.github.io/nungkup101/'
repo_name: 'nungkup101'
repo_url: 'https://github.com/thanakrit1997/nungkup101.git'

theme:
  name: material
  logo: images/nungkup-web-logo.png
  favicon: images/nungkup-web-logo.png
  font:
    text: ember
  palette:
    primary: blue
    accent: blue
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.tabs.sticky
  highlightjs: true
  hljs_languages:
    - yaml
    - json

plugins:
  - include-markdown
  - search:
      lang:
        - en
  - awesome-pages

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true